apiVersion: apps/v1
kind: Deployment
metadata:
  name: email_ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email_ms
  template:
    metadata:
      labels:
        app: email_ms
    spec:
      containers:
      - name: email_ms
        image: your-registry/users:latest #alterar
        ports:
        - containerPort: 80